services:
  - type: web
    name: buildfolio-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://buildfolio-one.vercel.app
      - key: GEMINI_API_KEY
        sync: false
